export const LOGIN = 'LOGIN'
export const ADD_PROFILE_PIC = 'ADD_PROFILE_PIC'
export const GET_ALL_ITEMS_GROUPS_SUCCESS = 'GET_ALL_ITEMS_GROUPS_SUCCESS'
export const GET_ALL_GROUPS_ITEMS = 'GET_ALL_GROUPS_ITEMS'
export const GET_ALL_ITEMS_GROUPS_ERROR = 'GET_ALL_ITEMS_GROUPS_ERROR'
export const ITEMS_NO_PRICES = 'ITEMS_NO_PRICES'
export const FAVORITE_ITEM = 'FAVORITE_ITEM'
export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST'
export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_PENDDING = 'ADD_TO_CART_PENDDING'

export const SEARCH_ITEM_CODE = 'SEARCH_ITEM_CODE'

export const PARTY_ITEMS = 'PARTY_ITEMS'


export const ADD_OTHER_DISCOUNT = 'ADD_OTHER_DISCOUNT'
export const INCREMENT_ITEM = 'INCREMENT_ITEM'
export const DECREMENT_ITEM = 'DECREMENT_ITEM'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const CHANGE_IMG = 'CHANGE_IMG'

export const FILTER_BY_GROUP = 'FILTER_BY_GROUP'
export const VIEW_ALL_ITEMS = 'VIEW_ALL_ITEMS'
export const ADD_LOOK_UPS = 'ADD_LOOK_UPS'


export const ADD_TO_ORDER = 'ADD_TO_ORDER'
export const ORDER_GET_ALL_ITEMS = 'ORDER_GET_ALL_ITEMS'

export const SET_ORDERS_API = 'SET_ORDERS_API'

export const OTHER_PARTY_SELECTION = 'OTHER_PARTY_SELECTION'

export const GET_PARTIES_SUCCESS = 'GET_PARTIES_SUCCESS'
export const GET_PARTIES_PENDING = 'GET_PARTIES_PENDING'
export const GET_PARTIES_ERROR = 'GET_PARTIES_ERROR'
export const UPDATE_PARTY_INFO = 'UPDATE_PARTY_INFO'
export const UPDATE_PARTY_IMAGE = 'UPDATE_PARTY_IMAGE'

export const SEARCH_PARTY = 'SEARCH_PARTY'


export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const PRINTER_SETTING = 'PRINTER_SETTING'

export const FILTER_GROUP = 'FILTER_GROUP'
export const VIEW_ALL_GROUPS = 'VIEW_ALL_GROUPS'



export const CREATION_DATA = 'CREATION_DATA'
export const GET_INVOICE_NUMBER = 'GET_INVOICE_NUMBER'

export const ADD_INVOICE_ITEMS = 'ADD_INVOICE_ITEMS'
export const REMOVE_FROM_ITEMS_INVOICE = 'REMOVE_FROM_ITEMS_INVOICE'
export const ADD_INVOICE = 'ADD_INVOICE'
export const VIEW_ALL_INVOICES = 'VIEW_ALL_INVOICES'
export const VIEW_INVOICE_DETAILS = 'VIEW_INVOICE_DETAILS'
